//============================================================================
// Name        : apcs.cpp
// Author      : 
// Version     :
// Copyright   : Your copyright notice
// Description : 邏輯判斷in C++, Ansi-style
//============================================================================

#include <iostream>
#include <iomanip>
using namespace std;

int main() {
	cout << (5>=2) << endl;
	cout << (5<=2) << endl;
	cout << (5>2) << endl;
	cout << (5<2) << endl;
	cout << (5==2) << endl;
	cout <<(5!=2) << endl;
 	return 0;
}
